/**************************************************************

 Project: 191_CreativeCoding
    File: _config.yml

  Author: Michael Musick
   Email: michael@michaelmusick.com

 Created: 2016-08-28 12:30:16
Modified: 2016-08-28 12:30:39


   Notes: 


**************************************************************/

theme: minima